version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-codeql-action:
        patterns:
        - github/codeql-action*
        update-types:
        - minor
        - patch
        exclude-patterns:
        - torch*
        - transformers
        - accelerate
        - vllm
        - unsloth*
        - openai
      szl-minor-patch:
        patterns:
        - '*'
        update-types:
        - minor
        - patch
        exclude-patterns:
        - torch*
        - transformers
        - accelerate
        - vllm
        - unsloth*
        - openai
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    cooldown:
      default-days: 3
